import type { Metadata } from "next";
import { Hanken_Grotesk } from "next/font/google";
import "./globals.css";
import { Header } from "~/components/header";
import { Sidebar } from "~/components/sidebar";
import { Footer } from "~/components/footer";
import { ThemeProvider } from "next-themes";
import { getData } from "@/lib/data-loader";

const hankenGrotesk = Hanken_Grotesk({
  variable: "--font-hanken-grotesk",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = await getData();
  const { personal_information, ui_content } = data;

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${hankenGrotesk.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem={false}
        >
          <Header />
          {/* <Sidebar /> */}
          <div style={{ paddingTop: "var(--header-height, 96px)" }}>
            {children}
          </div>
          <Footer
            personal_information={personal_information}
            ui_content={ui_content}
          />
        </ThemeProvider>
      </body>
    </html>
  );
}
